CREATE TABLE IF NOT EXISTS calculations (
  id SERIAL PRIMARY KEY,
  a DOUBLE PRECISION NOT NULL,
  b DOUBLE PRECISION NOT NULL,
  operation VARCHAR(20) NOT NULL,
  result DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);